version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - "37017:27017"  # Standard MongoDB port; consistent port mapping
    networks:
      - app-network

  backend:
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongodb   # Explicitly set the host for clarity
      - MONGO_PORT=27017      # Optional: can be useful for more flexibility
      - MONGO_DB_NAME=uncat #The name of the db
    ports:
      - "3000"
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "5173"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge